# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = EPub-Extractor
DESTDIR = ./x64/Debug
CONFIG += debug
DEFINES += _WINDOWS
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(EPub-Extractor.pri)
win32:RC_FILE = EPub-Extractor.rc
